"""core Store 逻辑切面:Challenge(业务) vs Control(调度)的内部边界。

物理上仍是一个 Store/一个 SQLite 文件(单写者硬约束,不做物理拆库):
本模块只用 Protocol 声明两类调用方各自允许的方法子集,防止跨层误调。
- ChallengeStorePort: ChallengeService 允许调用的方法;
- ControlStorePort: ControlPlaneService/调度 API 允许调用的方法。
新增 Store 方法时先归类到其一(或双实现并注明原因),不得新增第三个 CRUD 入口。
"""

from __future__ import annotations

from typing import Any, Protocol

from ghost.control.store import AssignmentRow, ChallengeRow, SubmissionRow


class ChallengeStorePort(Protocol):
    """题目/评分业务切面(challenges/submissions/tasks 表)。"""

    def has_task(self, token: str) -> bool: ...
    def task_is_active(self, token: str) -> bool: ...
    def stop_task(self, token: str) -> bool: ...
    def get_challenge(self, token: str, unique_code: str) -> ChallengeRow | None: ...
    def list_challenges(self, token: str) -> tuple[ChallengeRow, ...]: ...
    def active_container_count(self, token: str) -> int: ...
    def reserve_container(self, token: str, unique_code: str, max_active: int) -> str: ...
    def set_container(self, token: str, unique_code: str, status: str,
                      addresses: tuple[str, ...] = ...,
                      container_id: str | None = ...,
                      *, expect: tuple[str, ...] | None = ...) -> bool: ...
    def mark_hint_viewed(self, token: str, unique_code: str) -> None: ...
    def submissions(self, token: str, unique_code: str) -> tuple[SubmissionRow, ...]: ...
    def record_submission(self, token: str, unique_code: str, flag_index: int, awarded: int) -> None: ...


class ControlStorePort(Protocol):
    """调度切面(evaluations/jobs/attempts/workers/platform_events/outbox 表)。"""

    def create_evaluation(self, task_token: str, *, project_id: str = ...,
                          idempotency_key: str | None = ...) -> dict: ...
    def get_evaluation(self, evaluation_id: str) -> dict | None: ...
    def list_evaluations(self, project_id: str | None = ...) -> list[dict]: ...
    def cancel_evaluation(self, evaluation_id: str) -> dict | None: ...
    def register_worker(self, worker_id: str, capabilities: dict | None = ...) -> dict: ...
    def list_workers(self) -> list[dict]: ...
    def worker_heartbeat(self, worker_id: str, status: str = ...) -> bool: ...
    def claim_job(self, worker_id: str, lease_seconds: int = ...) -> AssignmentRow | None: ...
    def heartbeat_assignment(self, attempt_id: str, worker_id: str,
                             lease_id: str, lease_seconds: int = ...) -> bool: ...
    def append_attempt_events(self, attempt_id: str, worker_id: str,
                              lease_id: str, events: list) -> int: ...
    def attempt_context(self, attempt_id: str) -> dict | None: ...
    def complete_attempt(self, attempt_id: str, worker_id: str, lease_id: str, *,
                         status: str, solved: bool = ...,
                         flags_found: int | None = ...,
                         error: str | None = ...) -> dict: ...
    def attempt_events(self, attempt_id: str) -> list[dict]: ...
    def pending_outbox(self, limit: int = ...) -> list[dict]: ...
    def mark_outbox_delivered(self, event_ids: list[str]) -> int: ...


def check_store_facets(store: Any) -> tuple[bool, bool]:
    """断言 store 同时满足双切面(回归测试用,防方法漂移)。"""

    challenge_methods = (
        "has_task", "task_is_active", "stop_task", "get_challenge",
        "list_challenges", "active_container_count", "reserve_container",
        "set_container", "mark_hint_viewed", "submissions", "record_submission",
    )
    control_methods = (
        "create_evaluation", "get_evaluation", "list_evaluations",
        "cancel_evaluation", "register_worker", "list_workers",
        "worker_heartbeat", "claim_job", "heartbeat_assignment",
        "append_attempt_events", "attempt_context", "complete_attempt",
        "attempt_events", "pending_outbox", "mark_outbox_delivered",
    )
    return (
        all(callable(getattr(store, name, None)) for name in challenge_methods),
        all(callable(getattr(store, name, None)) for name in control_methods),
    )
