/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Banner: typeof import('./src/components/Banner.vue')['default']
    ChallengeList: typeof import('./src/components/ChallengeList.vue')['default']
    ChallengeRow: typeof import('./src/components/ChallengeRow.vue')['default']
    Chip: typeof import('./src/components/Chip.vue')['default']
    DiffBadge: typeof import('./src/components/DiffBadge.vue')['default']
    ElAlert: typeof import('element-plus/es')['ElAlert']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCollapse: typeof import('element-plus/es')['ElCollapse']
    ElCollapseItem: typeof import('element-plus/es')['ElCollapseItem']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTag: typeof import('element-plus/es')['ElTag']
    FlagRow: typeof import('./src/components/FlagRow.vue')['default']
    LiveChip: typeof import('./src/components/LiveChip.vue')['default']
    ReadAuthGate: typeof import('./src/components/ReadAuthGate.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    StatCard: typeof import('./src/components/StatCard.vue')['default']
    StatusTag: typeof import('./src/components/StatusTag.vue')['default']
    Timeline: typeof import('./src/components/detail/Timeline.vue')['default']
    TimelineRow: typeof import('./src/components/detail/TimelineRow.vue')['default']
    ToolRow: typeof import('./src/components/detail/ToolRow.vue')['default']
    TranscriptRaw: typeof import('./src/components/detail/TranscriptRaw.vue')['default']
  }
}
